### PR TITLE
feat: legendary deck

### PR DESCRIPTION
**Pull request by Luke-McMahon**
needs final artwork

for now, I've just added the soul card as the deck art

### CODE REVIEW

**Comment by Cooler2231** [comment]
gonna make art for this; do you have anywhere to be sent it so you can implement it?

**Comment by Foegro** [comment]
Sounds cool

**Comment by Luke-McMahon** [comment]
> gonna make art for this; do you have anywhere to be sent it so you can implement it?

Happy for you to send over the discord, otherwise you can contribute directly to the branch too

**Comment by Luke-McMahon** [comment]
Hey @Jevonnissocoolman, just wanted to check - do you know how/where we would check to get the rng to adhere to oops all 6s etc?

Right now, I don't think it would work, it would always remain a 1:5 chance

**Comment by Jevonnissocoolman** [comment]
> Hey @Jevonnissocoolman, just wanted to check - do you know how/where we would check to get the rng to adhere to oops all 6s etc?
> 
> Right now, I don't think it would work, it would always remain a 1:5 chance

Use G.GAME.probabilities.normal, some jokers in this mod use it so look there if you need anything else

**Comment by Luke-McMahon** [comment]
> gonna make art for this; do you have anywhere to be sent it so you can implement it?

@Cooler2231 if you are keen to help out with the art, jump in the discord and we can sort it out! Otherwise, I suggest we move forward with the temp art I've put in

**Comment by Jevonnissocoolman** [comment]
atlasdeck
Art was done a bit ago, this should be the updated 1x atlas with it included

**Comment by Jevonnissocoolman** [comment]
atlasdeck and this is the 2x

**Comment by Luke-McMahon** [comment]
@Jevonnissocoolman that's all done

**Comment by Cooler2231** [comment]
hey luke! sorry for not responding; that art thats currently in game is the art i was gonna post to you that i made.

**Comment by Cooler2231** [comment]
sorry for ignoring; it just took me a bit to see

**Comment by Cooler2231** [comment]
> > gonna make art for this; do you have anywhere to be sent it so you can implement it?
> 
> @Cooler2231 if you are keen to help out with the art, jump in the discord and we can sort it out! Otherwise, I suggest we move forward with the temp art I've put in

so sorry! the art that jevonn implemented was the art i made; couldn't get back to you :(

**Pull request merged**
