### PR TITLE
Membership Card

### PR DESCRIPTION
**Pull request by Toneblock**
requires someone to add "cryptid member counter" to the server

### CODE REVIEW

**Comment by Toneblock** [comment]
does not work with mac

**Review by stupxd — CHANGES_REQUESTED** [review]

**Review by stupxd — APPROVED** [review]
looks good now

**Comment by MathIsFun0** [comment]
added the bot, should be good to go surely

**Comment by Jevonnissocoolman** [comment]
Screenshot 2024-09-02 at 10 53 00 AM
I'm still getting this popup on load

**Comment by Jevonnissocoolman** [comment]
uh oh it got merged, might be too late now

**Comment by Toneblock** [comment]
uh

**Comment by Toneblock** [comment]
is the config disabled on launch

**Comment by Jevonnissocoolman** [comment]
doesn't appear to be
Might need to mess with config.lua

**Pull request merged**
