### PR TITLE
Fix type mismatch errors in shader code

### PR DESCRIPTION
**Pull request by PIPIKAI**
Refactored GLSL code to avoid implicit type conversions between float and int. Explicit type casting has been added to ensure compatibility with strict compilers.

### CODE REVIEW

**Comment by stupxd** [comment]
seems good to me 👍 thanks for the PR

**Comment by stupxd** [comment]
tho tbf, I wonder if you'd even be able to start the vanilla game, as some vanilla shaders have the same issue
you will have to override the vanilla shaders, I assume

**Comment by PIPIKAI** [comment]
I fixed this because I found that loose syntax might cause issues on the ARM architecture platform. I tested the pull request myself, and it's working fine.

**Comment by Jevonnissocoolman** [comment]
Testing this myself and so far not encountering any issues
I think is good to merge, good job

**Pull request merged**
