### PR TITLE
Added new rare Code joker "Cut", art by @Celeritas

### PR DESCRIPTION
**Pull request by AutoWatto**
art by @Celeritas; has been playtested.

### CODE REVIEW

**Comment by Jevonnissocoolman** [comment]
Why was night changed lmfao

**Comment by Toneblock** [comment]
this night nerf is horrible for the economy

**Comment by Jevonnissocoolman** [comment]
yeah change that back, I don't even think the description was changed either xd

**Comment by MathIsFun0** [comment]
Turned Night into a common Joker 💀

**Comment by AutoWatto** [comment]
Accidentally changed that value and didn't intend to lmao

**Comment by SDM0** [comment]
Grill this man!

**Comment by Jevonnissocoolman** [comment]
We won Mr. Stark
Also looking through this It seems lile this joker isn’t disabled if code cards are disabled so maybe that can be changed at some point
Same with Cut and Copy/Paste

**Comment by AutoWatto** [comment]
Truth be told as i was telling Math, I'm new to this so I have no idea how I'd go about that. if someone would help with that i'd greatly appreciate it.

**Comment by Jevonnissocoolman** [comment]
I think math will be able to handle that from here dw
You already did most of the heavy lifting here :balatrojoker:

**Comment by AutoWatto** [comment]
o7

**Pull request merged**
